build:
  image: maven:3.3.3
  command: mvn -Dprofile=foobar package
  sandbox: true
  artifacts:
    - target/my-app-1.0-SNAPSHOT.jar
container:
  base_image: java:8
  command: java -jar /application/service-1.0.0.jar
  artifacts:
    - target/service-1.0.0.jar
