dependencies:
  build:
    - go:1.12
  runtime:
    - go:1.12

targets:
  default:
    commands:
      - go build
  linux:
    env: 
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build -o artificer-linux-amd64

exec:
  commands:
    - ./artificer

