dependencies:
  build:
    - go:1.12
  runtime:
    - go:1.12

build_targets:
  - name: default
    commands:
      - go build

  - name: linux
    build_after: 
      - default
    tags:
      os: linux
    environment: 
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build -o artificer-linux-amd64

  - name: darwin
    tags:
      os: darwin
    environment:
      - GOOS=darwin
      - GOARCH=amd64
    commands:
      - go build -o artificer-darwin-amd64

exec:
  environment:
    default:
     - YOURBASE_API_URL=http://localhost:5000
     - YOURBASE_UI_URL=http://localhost:3000
     - DISPATCHER_URL=http://localhost:8080
     - YB_USER_TOKEN=ec21c5d6-c1c2-4a57-a92a-59a26cb9eb47
  commands:
    - ./artificer build

