dependencies:
  build:
    - go:1.13.4
    - python:3.6

build_targets:
  - name: default
    host_only: true
    commands:
      - go test ./...
      - go build

  - name: integration
    build_after:
      - default
    host_only: true
    commands:
      - bash -c "cd integration-tests; yb build -no-container"
      - bash -c "cd integration-tests; yb build -no-container python"
      - bash -c "cd integration-tests; yb build -no-container gopher"
      - bash -c "cd integration-tests; yb build -no-container ruby"
      - bash -c "cd integration-tests; yb build -no-container java"

  - name: release
    build_after:
      - default
    commands:
      - pip install awscli
      - bash release.sh 

  - name: linux
    build_after:
      - default
    tags:
      os: linux
    environment: 
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build -o yb-linux-amd64

  - name: darwin
    build_after:
      - default
    tags:
      os: darwin
    environment:
      - GOOS=darwin
      - GOARCH=amd64
    commands:
      - go build -o yb-darwin-amd64

ci:
  builds:
    - name: test_build
      build_target: default

    - name: test_integration
      build_target: integration

    - name: release
      build_target: release
      when: tagged IS true

